### PR TITLE
fix: Added loading state to useFormGql

### PR DESCRIPTION
**Pull request by mikekeehnen**

### CODE REVIEW

**Comment by paales** [comment]
I think this can already be achieved by: `formState.isSubmitting`

**Comment by mikekeehnen** [comment]
> I think this can already be achieved by: `formState.isSubmitting`

`isSubmitting` gets triggered on form submission and validation, not on the actual mutation loading state. Might be good to separate those values like this.

**Comment by paales** [comment]
@mikekeehnen Can PM me an example how this is used?

**Comment by paales** [comment]
No apparent use cases communicated.

**Pull request closed without merging**
