### PR TITLE
Solve TypeError: url?.startsWith is not a function

### PR DESCRIPTION
**Pull request by paales**

### CODE REVIEW

**Comment by paales** [comment]
@muzafferkilicaslan Creating a fix for the main branch now. Should be live today with a new release.

**Comment by muzafferkilicaslan** [comment]
@paales Thanks Mr. Paul, I will check tomorrow.

**Comment by muzafferkilicaslan** [comment]
@paales Hi Mr. Paul, i successfully installed 8.0.8 version. Thanks for your work, responses and reminder of new release.

**Comment by paales** [comment]
Awesome!

**Comment by muzafferkilicaslan** [comment]
@paales Hi Paul, I don't want to use Hygraph. I know, magento pagebuilder is not too good but it's more easy to use i think. So can I disable hypgraph for good? I also see your roadmap;

"Create a generic CMS integration framework, removing the hard Hygraph requirement"

can you help me to contact who's working on this?

**Pull request merged**
