### PR TITLE
Solve issue with url?.startsWith and various others

### PR DESCRIPTION
**Pull request by paales**

### CODE REVIEW

**Comment by paales** [comment]
@muzafferkilicaslan Yeah, had a priority thing to do, just pushed the latest changes. Not very happy with the required changes... See commit message here: https://github.com/graphcommerce-org/graphcommerce/pull/2380/commits/1b7cd40ca9096b8ed43c2035a8c7f5ae801a5968

**Comment by muzafferkilicaslan** [comment]
Hi @paales, i was checking and copying your changes to my locale at that commit but i have some questions. Is this doc is updated [https://www.graphcommerce.org/docs/getting-started/create](url) cause i was copying file by file but when [packages/cli/dist/bin/mesh.js](https://github.com/graphcommerce-org/graphcommerce/commit/1b7cd40ca9096b8ed43c2035a8c7f5ae801a5968#diff-95e2ec0b29870aedfa19661b7e157c10b87c98f03b88efd2d8c2cba573e36afc) looking this file changed file i mean original file isn't same my locale file. So i thought that doc might be outdated.

Also your last changes seems didn't fix all issues again. Could you help me to install and run Graphcommerce? I mean i can use old versions for now, if you advice me to another version of this i will be pre. I want to test GraphCommerce with my backend asap. Thanks :)

**Comment by paales** [comment]
@muzafferkilicaslan I'll provide a patch for the current 8.0.6 installation. But I _think_ you should be able to do the following:

1. Remove your current yarn.lock and node_modules directory.
2. Copy the yarn.lock from the main branch of this repo into your project directory.
3. Make sure you are using yarn 4, else it wont work. (`yarn set version berry`)
4. Run yarn install and the rest.

Can you test that out?

**Comment by muzafferkilicaslan** [comment]
@paales Hi Mr. Paul, thanks for your help but i couldn't run it. I'm probably continue with pwa-studio for now. But i will check graphcommerce again in a short time i hope.

**Pull request merged**
